[package]
name = "chonker95"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
eframe = "0.32.2"
egui = "0.32.2"
image = "0.25.2"
quick-xml = "0.38.3"
rfd = "0.15.4"
ropey = "1.6.1"
