[package]
name = "chonker95"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
arboard = "3.6.1"
bytemuck = "1.23.2"
eframe = "0.32.2"
egui = "0.32.2"
fontdue = "0.9.3"
itertools = "0.14.0"
pollster = "0.4.0"
quick-xml = "0.38.3"
rfd = "0.15.4"
ropey = "1.6.1"
smallvec = "1.15.1"
wgpu = "0.19"
wgpu_text = "26.0.0"
winit = "0.30.12"
