#!/bin/bash

echo "Testing chonker95 keybinding compatibility..."
echo ""
echo "Key mappings disabled in Kitty:"
echo "✓ Cmd+C/X/V/A - Now handled by chonker95"
echo "✓ Cmd+Q - Now handled by chonker95"
echo "✓ Ctrl+Left/Right - Page navigation in chonker95"
echo "✓ Alt+Left/Right - Viewport scrolling in chonker95"
echo "✓ Page Up/Down - Viewport scrolling in chonker95"
echo "✓ Arrow keys - Cursor movement in chonker95"
echo "✓ Home/End - Line navigation in chonker95"
echo "✓ Escape - Selection clearing in chonker95"
echo ""
echo "Alternative Kitty shortcuts available:"
echo "• Cmd+Shift+C/X/V/A - Kitty clipboard operations"
echo "• Cmd+Shift+Q - Quit Kitty"
echo ""
echo "Ready to test chonker95!"
echo "Run: DYLD_LIBRARY_PATH=/Users/jack/chonker95/lib /Users/jack/chonker95/target/release/chonker95 your-file.pdf"